apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekF4TWpZeApOVFF4TXpKYUZ3MDBNekF4TWpZeE5UUXhNekphTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEa0hMVUZlRjAxUlZJcWlJTnY3VTk3YTNYZHNJcC96MDN5RnM4eTdBS3c5RS9IQlVjdgpFL0RNUEJwMVBGRDlmeW42WWdOMnlSL0JZemFYanVZa3FDVXVUTjZyeFZlOW9YWXJzc2NTQmNsWlFDK2dKY0xYCjRHSFhnRTVKcXA3MmZ2TWIyM094VlNlWHozWkhlaTEvM3RzSlkwcmJEUndVdWQ0enlhNlVXOVZYNTVTYzRpWjUKV0h2cmpWWndSSzdDRXVHSFBSaGZVUFZQbGd5aDM3QXpnK0VFY05sSUQ5NEM3OUJVU1pTVWJwNVo4WHEzRWhPdApKdEY3dXh5bFJaMHpUSHNBLzU2WW5ZUGtzNENQanV1UG5WbWhwSjR0UG12QUxUc1JFcm1xUGRHZ3I1QkVQM01MCmxDb0F1QWFBb1cyd3ZYOVNkS1lJbDBIYzJicXJIRDBGQzJVaEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlJSRFVSVlVFZ3FHRTZpY1lyeAp5RDNQNWljNEZ6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFXYzVYZXpuSDBMTmFvUWZkTERxSk1mK1NrbDdPCmRrdVVDYTlNa0JGcmhCU1BYZmowVElFeVhRNzlxV1VrQlhyZFROaUNNUWVlN1NQWGI1bGJkeHo2WWdBdmN2QVkKREt4NDZua3FFVXhpYmgvd3BGaUsxcm8wMHRuOTYzaHV2NmJYOVA1cjFBOVdnTTlsaFBubFRYbU5YbGpvckFQVApoQzZ1aitjKzhreENxdDE2bFVNaC9JTzhCODlMWjkwd0JDTi8zUGxJalg5SlBoNTlQY3lmM3p5K2FQM24yS1VDCmhTWE5XQUlrVFVydHp4bk5vamVIRndUQU5yWDlpT2dWTTN6VVV2L0lLU2JpZkxLbGNPVnBjRmFoQWlMUUdncVMKTk0wMzc4bytMeWZDQStnOGEyNnAwbDhQTENCM0dwOS9vVk9TV2pyeEtlNFplY0xWRDBFdTIxc2ErQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://352984a7-4abb-4b37-af20-231f495b5da8.k8s.ondigitalocean.com
  name: do-nyc1-k8s
contexts:
- context:
    cluster: do-nyc1-k8s
    user: do-nyc1-k8s-admin
  name: do-nyc1-k8s
current-context: do-nyc1-k8s
users:
- name: do-nyc1-k8s-admin
  user:
    token: dop_v1_57af7846bbbe7e730ac6e47c8814ef65026167a7b6ce459cf43ab6edcf572ca8
